In [1]:
import numpy as np

## Задание 1

In [2]:
n_ar = np.arange(0 , 10)

In [3]:
n_ar[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

In [4]:
n_diag = np.diag(np.arange(2, 50, 8))

In [5]:
sum_mat = n_diag[::-1]
sum_mat

array([[ 0,  0,  0,  0,  0, 42],
       [ 0,  0,  0,  0, 34,  0],
       [ 0,  0,  0, 26,  0,  0],
       [ 0,  0, 18,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0,  0]])

In [6]:
sum_mat.sum()

132

## Задание 3

In [7]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [8]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [9]:
# решение

from numpy import linalg

In [10]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задание 4

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [13]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [14]:
def cosine( users_stats, next_user_stats ):
    # длины векторов
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )

In [15]:
muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)

In [16]:
best_user = np.argmax(muls)

best_user

7